// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkmtuejbztsfwzcagyzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbXR1ZWpienRzZnd6Y2FneXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzAxOTksImV4cCI6MjA2MjU0NjE5OX0.x8OeycBQYLKhfqE2Xw8CI9fI7-jrDP4AnQXurG-P3lY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);